import org.junit.Test;
import org.pack.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'neto' at '7/2/16 12:45 AM' with Gradle 2.14
 *
 * @author neto, @date 7/2/16 12:45 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
